services:
  orchestrator:
    build: ./orchestrator
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - APP_URL
    ports:
      - 3000:4000

  app:
    build: ./services/app
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=4001
      - JWT_SECRET_KEY
      - DATABASE_URL
    ports:
      - 3001:4001
