services:
  orchestrator:
    build: ./orchestrator
    environment:
      - NODE_ENV=production
      - PORT=4000

  app:
    build: ./services/app
    environment:
      - NODE_ENV=production
      - PORT=4001
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - APP_URL=${APP_URL}
